const levelList = [
    {
        id: 0,
        name: "Select Level",
        description: "level 0",
        construct: new Level0(),
        isStarted: true,
        hasKey: false,
    }, 
    {
        id: 1,
        name: "Level 1",
        description: "find the exit",
        construct: new Level1(),
        isStarted: true,
        hasKey: true,
    }, 
    {
        id: 2,
        name: "Level 2",
        description: "find a way to access the exit",
        construct: new Level2(),
        isStarted: false,
        hasKey: false,
        
    }, 
    {
        id: 3,
        name: "Level 3",
        description: "the floor is lava",
        construct: new Level3(),
        isStarted: false,
        hasKey: false,
    },
    {
        id: 4,
        name: "Level 4",
        description: "wait for it",
        construct: new Level4(),
        isStarted: false,
        hasKey: false,
    },
    {
        id: 5,
        name: "Level 5",
        description: "more difficult",
        construct: new Level5(),
        isStarted: false,
        hasKey: false,
    },
    {
        id: 6,
        name: "Level 6",
        description: "Start is exit",
        construct: new Level6(),
        isStarted: false,
        hasKey: false,
    },
    {
        id: 7,
        name: "Level 7",
        description: "don't trust your eyes",
        construct: new Level7(),
        isStarted: false,
        hasKey: false,
    },
    {
        id: 8,
        name: "Level 8",
        description: "press on That level",
        construct: new Level8(),
        isStarted: false,
        hasKey: false,
    },
]